version: 2
enable-beta-ecosystems: true

updates:
  # Apps
  - package-ecosystem: "pub"
    directory: "."
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    versioning-strategy: increase
