name: kovidoverlook
description: A new Flutter application for Flutter Vietnam UI Challenge #1.
version: 1.0.0+1
authors:
  - Kianto

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  intl: 0.16.1
  shimmer: ^1.1.1
  fl_chart: 0.11.0
  http: 0.12.2
  carousel_slider: 2.2.1

  flutter_launcher_icons: 0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/data/countries.json


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

